### ISSUE TITLE
LEARN TO CODE STOP USING CURSOR!!!!

### ISSUE THREAD

**Issue by ariakh55** [omidnw/room-organizer#1]
LEARN HOW TO CODE PIECE OF SHIT

**Comment by omidnw** [comment]
Anything that can save your time, energy, and brainpower should be utilized—whether it’s LLM models, cursor IDE, or their agents.

Instead of spending time on repetitive tasks or trying to write reusable code for other projects (which rarely ever happens), you can create quick, one-off, and practical code with minimal effort.

Proper use of these tools can also provide you with clean snippets of code to get your tasks done quickly. These pieces can later serve as puzzle pieces you can incorporate into other projects.
